// Build-time artwork only: Waybar's native modules supply usage, capacity and signal.
// Run with `node dotfiles/.config/waybar/scripts/generate-gauges.mjs`.
import fs from 'node:fs';

const root = new URL('../', import.meta.url);
const assets = new URL('gauges/', root);
fs.mkdirSync(assets, { recursive: true });

function svg(mode, usage) {
  const radius = 9.2;
  const start = mode === 'arc' ? 135 : -90;
  const sweep = mode === 'arc' ? 270 : 359.99;
  const point = angle => [
    12 + radius * Math.cos(angle * Math.PI / 180),
    12 + radius * Math.sin(angle * Math.PI / 180),
  ].map(n => n.toFixed(3)).join(' ');
  const path = angle => `M ${point(start)} A ${radius} ${radius} 0 ${angle > 180 ? 1 : 0} 1 ${point(start + angle)}`;
  const color = usage >= 90 ? '#ef8585' : usage >= 75 ? '#e7bc6b' : '#eeeeee';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
  <g fill="none" stroke-width="1.8" stroke-linecap="round">
    <path d="${path(sweep)}" stroke="#606369"/>
${usage ? `    <path d="${path(sweep * usage / 100)}" stroke="${color}"/>\n` : ''}  </g>
</svg>
`;
}
// Classic Wi-Fi silhouette: three separate concentric arcs and a round dot.
// Keep unlit arcs faint so all four signal levels have the same visual footprint.
function wifiSvg(level) {
  const off = level === null;
  const arcs = [5.4, 10.2, 15].map((radius, index) => {
    const x = radius / Math.SQRT2;
    const y = 19.5 - x;
    const color = off ? '#92969c' : index < level ? '#eeeeee' : '#62676d';
    return `    <path d="M ${(12 - x).toFixed(3)} ${y.toFixed(3)} A ${radius} ${radius} 0 0 1 ${(12 + x).toFixed(3)} ${y.toFixed(3)}" stroke="${color}"/>`;
  }).join('\n');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
${off ? `  <defs><mask id="slash-gap"><rect width="24" height="24" fill="white"/><path d="M3 3l18 18" stroke="black" stroke-width="5"/></mask></defs>\n` : ''}  <g fill="none" stroke-width="2.4" stroke-linecap="round"${off ? ' mask="url(#slash-gap)"' : ''}>
${arcs}
    <circle cx="12" cy="19.5" r="1.6" fill="${off ? '#92969c' : '#eeeeee'}"/>
  </g>
${off ? '  <path d="M3 3l18 18" fill="none" stroke="#92969c" stroke-width="2.4" stroke-linecap="round"/>\n' : ''}</svg>
`;
}

const startMarker = '/* BEGIN GENERATED USAGE GAUGES */';
const endMarker = '/* END GENERATED USAGE GAUGES */';
let css = `${startMarker}
/* Generated by scripts/generate-gauges.mjs; edit that file to change artwork.
   config.jsonc's name selects gauges-ring or gauges-arc. */
#cpu, #memory {
  min-width: 22px;
  min-height: 22px;
  margin: 0 2px;
  padding: 0;
  /* The old FontAwesome name falls back to a patched monospace font whose
     icon ink extends beyond its advance width. Select the installed face. */
  font-family: "Font Awesome 7 Free";
  font-weight: 900;
  font-size: 10px;
  background-size: 22px 22px;
  background-position: center;
  background-repeat: no-repeat;
}
/* Compact gaps from Wi-Fi through the CPU/memory pair. */
#cpu { margin-left: 1px; margin-right: 1px; }
#memory { margin-left: 1px; }
`;
for (const mode of ['ring', 'arc']) {
  for (let usage = 0; usage <= 100; usage += 5) {
    const file = `${mode}-${usage}.svg`;
    fs.writeFileSync(new URL(file, assets), svg(mode, usage));
    css += `window.gauges-${mode} #cpu.gauge${usage},
window.gauges-${mode} #memory.gauge${usage} {
  background-image: url("gauges/${file}");
}
`;
  }
}
css += `
/* Native network states select separate curved bars, matching the old Wi-Fi icon. */
#network.signal {
  background-image: url("gauges/wifi-off.svg");
  background-size: 18px 18px;
  background-position: center;
  background-repeat: no-repeat;
}
#network.signal.ethernet { background-image: none; }
`;
fs.writeFileSync(new URL('wifi-off.svg', assets), wifiSvg(null));
for (let level = 0; level < 4; level++) {
  const file = `wifi-${level}.svg`;
  fs.writeFileSync(new URL(file, assets), wifiSvg(level));
  css += `#network.signal.wifi.signal${level * 25},
#network.signal.linked.signal${level * 25} {
  background-image: url("gauges/${file}");
}
`;
}
// Lucide's battery outline, widened to make room for the live percentage.
// https://github.com/lucide-icons/lucide/blob/main/icons/battery.svg
// See gauges/LUCIDE-LICENSE. The fill is CSS, so only three SVGs are needed.
for (const [name, color] of Object.entries({
  normal: '#dce1e7', low: '#ef8585', charging: '#8fdf8f',
})) {
  fs.writeFileSync(new URL(`battery-${name}.svg`, assets),
    `<svg xmlns="http://www.w3.org/2000/svg" width="64" height="18" viewBox="0 0 64 18" fill="none" stroke="${color}" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
  <rect x="1" y="1" width="58" height="16" rx="3"/>
  <path d="M62 6v6"/>
</svg>
`);
}
css += `
/* Both native labels sit inside one outline. Mirrored battery states let the
   group retain capacity fill and charging/low colors across the whole body. */
#power {
  min-width: 64px;
  min-height: 22px;
  margin: 0 3px;
  padding: 0;
  background-image: url("gauges/battery-normal.svg"), linear-gradient(rgba(220, 225, 231, 0.25), rgba(220, 225, 231, 0.25));
  background-size: 64px 18px, 0 12px;
  background-position: center, 3px center;
  background-repeat: no-repeat;
}
#battery {
  min-width: 40px;
  min-height: 22px;
  margin: 0 0 0 3px;
  padding: 0;
  font-family: "DejaVu Sans", sans-serif;
  font-size: 10px;
  font-weight: 600;
  color: #eeeeee;
  animation: none;
  background: none;
}
#power.battery-level0, #power.battery-level10 {
  background-image: url("gauges/battery-low.svg"), linear-gradient(rgba(239, 133, 133, 0.3), rgba(239, 133, 133, 0.3));
}
#power.battery-charging {
  background-image: url("gauges/battery-charging.svg"), linear-gradient(rgba(143, 223, 143, 0.25), rgba(143, 223, 143, 0.25));
}
#battery.level0, #battery.level10 { color: #ef8585; }
#battery.charging { color: #8fdf8f; }
#power-profiles-daemon {
  min-width: 14px;
  min-height: 22px;
  margin: 0 7px 0 0;
  padding: 0;
  font-family: "Font Awesome 7 Free";
  font-weight: 900;
  font-size: 10px;
}
`;
for (let capacity = 0; capacity <= 100; capacity += 10) {
  css += `#power.battery-level${capacity} { background-size: 64px 18px, ${54 * capacity / 100}px 12px; }\n`;
}
css += endMarker;
const stylesheet = new URL('style.css', root);
const previous = fs.readFileSync(stylesheet, 'utf8');
const start = previous.indexOf(startMarker);
const end = previous.indexOf(endMarker);
if ((start < 0) !== (end < 0) || (start >= 0 && end < start)) {
  throw new Error('Incomplete generated gauge block in style.css');
}
fs.writeFileSync(stylesheet, start < 0
  ? `${previous.trimEnd()}\n\n${css}\n`
  : previous.slice(0, start) + css + previous.slice(end + endMarker.length));
