// Build-time artwork only: Waybar's native modules supply usage and capacity.
// Run with `node dotfiles/.config/waybar/scripts/generate-gauges.mjs`.
import fs from 'node:fs';

const root = new URL('../', import.meta.url);
const assets = new URL('gauges/', root);
fs.mkdirSync(assets, { recursive: true });

function svg(mode, usage) {
  const radius = 9.2;
  const start = mode === 'arc' ? 135 : -90;
  const sweep = mode === 'arc' ? 270 : 359.99;
  const point = angle => [
    12 + radius * Math.cos(angle * Math.PI / 180),
    12 + radius * Math.sin(angle * Math.PI / 180),
  ].map(n => n.toFixed(3)).join(' ');
  const path = angle => `M ${point(start)} A ${radius} ${radius} 0 ${angle > 180 ? 1 : 0} 1 ${point(start + angle)}`;
  const color = usage >= 90 ? '#ef8585' : usage >= 75 ? '#e7bc6b' : '#eeeeee';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
  <g fill="none" stroke-width="1.8" stroke-linecap="round">
    <path d="${path(sweep)}" stroke="#606369"/>
${usage ? `    <path d="${path(sweep * usage / 100)}" stroke="${color}"/>\n` : ''}  </g>
</svg>
`;
}

const startMarker = '/* BEGIN GENERATED USAGE GAUGES */';
const endMarker = '/* END GENERATED USAGE GAUGES */';
let css = `${startMarker}
/* Generated by scripts/generate-gauges.mjs; edit that file to change artwork.
   config.jsonc's name selects gauges-ring or gauges-arc. */
#cpu, #memory {
  min-width: 22px;
  min-height: 22px;
  margin: 0 2px;
  padding: 0;
  /* The old FontAwesome name falls back to a patched monospace font whose
     icon ink extends beyond its advance width. Select the installed face. */
  font-family: "Font Awesome 7 Free";
  font-weight: 900;
  font-size: 10px;
  background-size: 22px 22px;
  background-position: center;
  background-repeat: no-repeat;
}
`;
for (const mode of ['ring', 'arc']) {
  for (let usage = 0; usage <= 100; usage += 5) {
    const file = `${mode}-${usage}.svg`;
    fs.writeFileSync(new URL(file, assets), svg(mode, usage));
    css += `window.gauges-${mode} #cpu.gauge${usage},
window.gauges-${mode} #memory.gauge${usage} {
  background-image: url("gauges/${file}");
}
`;
  }
}
// Lucide's battery outline, widened to make room for the live percentage.
// https://github.com/lucide-icons/lucide/blob/main/icons/battery.svg
// See gauges/LUCIDE-LICENSE. The fill is CSS, so only three SVGs are needed.
for (const [name, color] of Object.entries({
  normal: '#dce1e7', low: '#ef8585', charging: '#8fdf8f',
})) {
  fs.writeFileSync(new URL(`battery-${name}.svg`, assets),
    `<svg xmlns="http://www.w3.org/2000/svg" width="44" height="18" viewBox="0 0 44 18" fill="none" stroke="${color}" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
  <rect x="1" y="1" width="38" height="16" rx="3"/>
  <path d="M42 6v6"/>
</svg>
`);
}
css += `
/* Keep the number centered in the body, excluding the terminal on the right.
   The second background is a translucent fill inside the battery outline. */
#battery {
  min-width: 40px;
  min-height: 22px;
  margin: 0 3px;
  padding: 0 4px 0 0;
  font-family: "DejaVu Sans", sans-serif;
  font-size: 10px;
  font-weight: 600;
  color: #eeeeee;
  animation: none;
  background-image: url("gauges/battery-normal.svg"), linear-gradient(rgba(220, 225, 231, 0.25), rgba(220, 225, 231, 0.25));
  background-size: 44px 18px, 0 12px;
  background-position: center, 3px center;
  background-repeat: no-repeat;
}
#battery.level0, #battery.level10 {
  color: #ef8585;
  background-image: url("gauges/battery-low.svg"), linear-gradient(rgba(239, 133, 133, 0.3), rgba(239, 133, 133, 0.3));
}
#battery.charging {
  color: #8fdf8f;
  background-image: url("gauges/battery-charging.svg"), linear-gradient(rgba(143, 223, 143, 0.25), rgba(143, 223, 143, 0.25));
}
`;
for (let capacity = 0; capacity <= 100; capacity += 10) {
  css += `#battery.level${capacity} { background-size: 44px 18px, ${35 * capacity / 100}px 12px; }\n`;
}
css += endMarker;
const stylesheet = new URL('style.css', root);
const previous = fs.readFileSync(stylesheet, 'utf8');
const start = previous.indexOf(startMarker);
const end = previous.indexOf(endMarker);
if ((start < 0) !== (end < 0) || (start >= 0 && end < start)) {
  throw new Error('Incomplete generated gauge block in style.css');
}
fs.writeFileSync(stylesheet, start < 0
  ? `${previous.trimEnd()}\n\n${css}\n`
  : previous.slice(0, start) + css + previous.slice(end + endMarker.length));
