# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
      kernelModules = [ "dm-snapshot" ];
      
      # Encrypted Disk, loaded at initrd
      luks.devices.root = {
        device = "/dev/disk/by-uuid/c45d1ad7-da38-4329-8fd5-88914f5e199f";
        preLVM = true;
        allowDiscards = true;
      };
    };

    kernelModules = [ "kvm-amd" ]; # "vfio_virqfd" "vfio_pci" "vfio_iommu_type1" "vfio" ];
    extraModulePackages = [ ];
    # extraModprobeConfig = "options vfio-pci ids=1002:73ff";

    kernelParams = [ "amd_iommu=on" ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ba0cc68b-5d0f-4838-9a39-7b1feb30fc04";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9CCA-8F2C";
    fsType = "vfat";
  };

  swapDevices = [ 
    { device = "/dev/disk/by-uuid/56a3b02a-30b1-4c61-ad7a-dd730c78143a"; } # Swap partition
    { device = "/dev/mapper/zyandrive-swap2"; } # Encrypted Swap (b.c. i didn't feel like resizing pv)
  ];
}
